//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfContractWork.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contract()
        {
            this.Responsible = new HashSet<Responsible>();
        }
    
        public int code { get; set; }
        public string title { get; set; }
        public string date_of_conclusion { get; set; }
        public string ending_date { get; set; }
        public decimal summ { get; set; }
        public int id_status { get; set; }
        public int id_type { get; set; }
    
        public virtual Contract_Status Contract_Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Responsible> Responsible { get; set; }
        public virtual Type_Of_Contract Type_Of_Contract { get; set; }
    }
}
