//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfContractWork.BD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Contract_WorkEntities : DbContext
    {
        private static Contract_WorkEntities _context;
        public Contract_WorkEntities()
            : base("name=Contract_WorkEntities")
        {
        }

        public static Contract_WorkEntities GetContext()
        {
            if (_context == null)
            {
                _context = new Contract_WorkEntities();
            }
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Contract> Contract { get; set; }
        public virtual DbSet<Contract_Status> Contract_Status { get; set; }
        public virtual DbSet<Responsible> Responsible { get; set; }
        public virtual DbSet<Type_Of_Contract> Type_Of_Contract { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
    }
}
