//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfContractWork.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Responsible
    {
        public int id_responsible { get; set; }
        public int code { get; set; }
        public int id_employee { get; set; }
        public string fio { get; set; }
    
        public virtual Contract Contract { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
